# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('a', 'Aktif'), ('i', 'Tidak Aktif')], default='a', max_length=1),
        ),
    ]
