# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_material_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Content'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('a', 'Aktif'), ('i', 'Tidak Aktif')], default='a', max_length=1),
        ),
    ]
