# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_auto_20161115_1509'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_point', models.PositiveIntegerField(default=100)),
                ('pass_grade', models.PositiveIntegerField(null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Content')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_point', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(default='t', max_length=1)),
                ('choice1', models.CharField(max_length=255, null=True)),
                ('choice2', models.CharField(max_length=255, null=True)),
                ('choice3', models.CharField(max_length=255, null=True)),
                ('choice4', models.CharField(max_length=255, null=True)),
                ('choice5', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(default='a', max_length=1)),
                ('status', models.CharField(default='a', max_length=1)),
                ('assignment_quest', models.ManyToManyField(through='assignment.AssignmentQuestion', to='assignment.Assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestionWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True)),
                ('filename', models.FileField(null=True, upload_to='')),
                ('point', models.FloatField(null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='a', max_length=1)),
                ('assignment_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.AssignmentQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_point', models.FloatField(default=0, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('status', models.CharField(default='a', max_length=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.AddField(
            model_name='studentquestionwork',
            name='student_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.StudentWork'),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.QuestionBank'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_work',
            field=models.ManyToManyField(through='assignment.StudentWork', to='member.Member'),
        ),
    ]
