# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Content'),
        ),
    ]
